# ~/.config/starship.toml
# https://starship.rs/

# no newline between prompts
add_newline = false

format = """$shlvl$time$all"""

[line_break]
disabled = true

[time]
disabled = false
time_format = "%I:%M:%S"
format = "[$time]($style) "

[directory]
truncation_length = 1
home_symbol="\b"

[git_branch]
format = "[$symbol$branch]($style) "

[battery]
disabled = true

[hostname]
style="bold green"
format = "[$hostname]($style) "

[username]
style_user="bold green"
format = "[$user@]($style)"

[shlvl]
disabled = false
style = "bold red"
format = "[$shlvl]($style) "
threshold = 2
