# ~/.config/starship.toml
# https://starship.rs/

# no newline between prompts
add_newline = false

format = """$character"""

# move the rest of the prompt to the right
right_format = """$all$time"""

[time]
disabled = false
time_format = "%I:%M:%S"
format = "[$time]($style)"

[directory]
truncation_length = 1

[git_branch]
format = "[$symbol$branch]($style) "

[battery]
disabled = true

[hostname]
style="bold dimmed grey"
format = "[$hostname]($style) "

[username]
format = "[$user]($style) "
